// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Mon Apr 27 21:01:12 2020

M25AA010A M25AA010A_inst
(
	.SI(SI_sig) ,	// input  SI_sig
	.SO(SO_sig) ,	// output  SO_sig
	.SCK(SCK_sig) ,	// input  SCK_sig
	.CS_N(CS_N_sig) ,	// input  CS_N_sig
	.WP_N(WP_N_sig) ,	// input  WP_N_sig
	.HOLD_N(HOLD_N_sig) ,	// input  HOLD_N_sig
	.RESET(RESET_sig) 	// input  RESET_sig
);

